### PR TITLE
Support 2D array serialization

### LINKED ISSUE #80: Add 2D array serialization
Only 1D arrays can be serialized currently; 2D would be useful (and any-dimensional would be best, but... baby steps!).

I already have an implementation, I'll submit a PR shortly.

### PR DESCRIPTION
**Pull request by hymerman**
Support 2D array serialization

Add unit tests to demonstrate 1D and 2D array serialization

Fix #80

### CODE REVIEW

**Comment by jacobdufault** [comment]
What about serializing this as a list of lists?

Can we scale this up to n-dimensional arrays?

**Comment by hymerman** [comment]
I thought about a list of lists, but decided against it because it seemed more appropriate for `[][]` arrays rather than `[,]` arrays, and because it adds to the serialized size. Not a big deal I know!

It certainly could be scaled up to n-dimensional arrays - I just wrote this because my object graph had 2D arrays so I needed it, I haven't encountered any 3+ dimensional arrays. It's up to you if you merge or not of course - I probably won't generalise this until I need it though, sorry :/ (total lack of free time!)

**Comment by jacobdufault** [comment]
Thinking about it more, I think I prefer serializing as a list of lists because it lets you swap swap [][] and [,] interchangeably without creating a versioned model.

I'll be happy to accept the PR if you change the serialization model to the list of lists. I'm fine with only 2D array support for now, but if you find the time to generalize it that'd be great :).

**Comment by hymerman** [comment]
Oh, I remember the actual reason now - it's because `[,]` is always rectangular, whereas `[][]` is an array of arrays where each inner array could be a different length. It can still be done, there will just be some ugly logic when it comes time to create the 2D array using `Array.CreateInstance(type, rows, columns)`!

**Comment by jacobdufault** [comment]
I think it's still worth adding the additional logic in that scenario, since having compatible serialization data is a very compelling argument. I think that if dimensions don't match up in the JSON file, then set the missing elements to the default and emit a warning.

**Comment by ajrb** [comment]
Is this in a released version anywhere?

**Comment by hymerman** [comment]
Nope - I never found the time (or need) to make the additional changes to get this PR accepted... I'd just fork this repo, add mine (and others) as remotes, and create your own branch merging whichever feature branches you fancy, that's what I've done :)

**Pull request merged**
