### PR TITLE
- option for serializing long and ulong as string

### PR DESCRIPTION
**Pull request by darress**

### CODE REVIEW

**Comment by jacobdufault** [comment]
Hey, thanks for the pull requests!

What's the motivation behind this? Do certain long values not serialize/deserialize properly as non-strings?

**Comment by jacobdufault** [comment]
Also, can you rebase to master? Looks like there are merge conflicts after merging the other PR.

**Comment by darress** [comment]
It was necessary for PHP compatibility. PHP does not support 64 bit ints at all without extensions.

I also rebased the branch as requested.

**Comment by jacobdufault** [comment]
sgtm, thanks

**Pull request merged**
