### PR TITLE
fix type converters not getting used for Dictionary entries that have be...

### PR DESCRIPTION
**Pull request by sharkyx**
...en mangled by fsIDictionaryAdapter

### CODE REVIEW

**Comment by jacobdufault** [comment]
Thanks for the pull request. Would you mind posting a test case that shows the broken behavior?

**Comment by jacobdufault** [comment]
Does the following still serialize correctly?

```c#
var container = new Dictionary<string, object>();
container["1"] = 3.0f;
container["2"] = false;
```

**Comment by sharkyx** [comment]
It serializes to
```
[ {    "Key": "1",
        "Value": 3.0
    },
    {   "Key": "2",
        "Value": false
    }]
```
without specifiying a typeconverter.

**Comment by sharkyx** [comment]
Ok so deserializing with the patched KeyValuePair converter doesn't work right now because I didn't do that part yet (sorry for the premature pull request). Doesn't seem trivial to add either since the storageType I get there is `fsIDictionaryAdapter.DictionaryItem` which doesn't allow me to reconstruct the correct types in the KeyValuePairConverter. 

The types should be available somewhere though, since they are passed in to the original TryDeserialize call. It's only after the data passes through the fsIEnumerableConverter the type information gets lost/hidden/overriden. Can you help me out there?

My goal is to get natural JSON output without typeinformation and without a simple key/value pair getting serialized to what we have above.

My initial problem was that I use a struct as an Id for typesafety like so:

`struct Id<T> { public int value; }` so that Ids of various contexts can't get mixed up accidently in code. I use these IDs as keys as well as values in various places.

As keys they get serialized like this:
```
	"Key": {
		"$content": 1,
		"$type": "rtimpl.Model.Id`1[[rtimpl.Model.StateDef, rtimpl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"
	},
	"Value": {
		"$content": false,
		"$type": "System.Boolean"
	}
```

What I want is simpy:
```
  "1" : false
```
  
Here is the typeconverter I wrote that I thought helps:
https://gist.github.com/sharkyx/e2eb7ede6f814a05f698

But it doesn't get applied, because the fsIEnumerableConverter gets in between hence my attempt at patching KeyValuePairConverter to be able to work with fsIEnumerableConverter output.

**Comment by jacobdufault** [comment]
The serialization can be reduced to

```json
[
    {
        "Key": "1",
        "Value": {
            "$content": 3.0,
            "$type": "System.Single"
        }
    },
    {
        "Key": "2",
        "Value": {
            "$content": false,
            "$type": "System.Boolean"
        }
    }
]
```

but we still have to encode type information for value since the object type does not match the storage type (for the key, objectType = string, storageType = string, so we can emit the type info, but for the value, objectType = <varies>, storageType = object).

I can take a look into getting the output down to that, but beyond that I don't think it can be made more minimal and still allow for full deserialization.

**Comment by jacobdufault** [comment]
Also, also a note `SortedDictionary` and the like have buggy iterator implementations, so the current serializer implementation has some workarounds so that they can serialize/deserialize as expected.

**Comment by jacobdufault** [comment]
I've added object-based dictionary serialization. It'll activate if the converter returns a string (I'll also likely make it work for all of the literal types).

**Pull request closed without merging**
